### PR TITLE
Open link on text and image tap too

### PR DESCRIPTION
**Pull request by felixgabler**
Should I make this configurable through some parameters? Also, can the `data.link` ever be null?

### CODE REVIEW

**Comment by demchenkoalex** [comment]
why is it needed exactly? we had that before and removed it in favour of a link, cause the tappable area of text and image is huge and it resulted in tons of unwanted taps.

**Comment by felixgabler** [comment]
Oh, I didn't know you had it. At my project, we had users think it is a bug that it's not tappable because all the other modern chat apps open their previews when the image or the title is tapped. It basically is as if the title is a link itself.

**Comment by demchenkoalex** [comment]
That's why link has a different style and is highlighted. In Telegram only links are tappable. In Facebook Messenger there is no preview at all, but links are highlighted too. On the other hand when we had that before, and I installed the app on the phone, I would click literally every link while scrolling the chat (if a lot of links is sent) so this can be an option maybe, but definitely not a default behaviour.

**Comment by felixgabler** [comment]
Definitely, I can make it optional

**Comment by felixgabler** [comment]
I have now made it optional. Is this better?

**Review by demchenkoalex — APPROVED** [review]

**Comment by demchenkoalex** [comment]
Thanks for the PR!

**Comment by demchenkoalex** [comment]
Renamed to `openOnPreviewImageTap` and `openOnPreviewTitleTap` since there is no "click" in mobile :)

**Pull request merged**
